/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PilatchCard {}
  interface PilatchCardAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'PilatchCard': Components.PilatchCard;
  }

  interface StencilIntrinsicElements {
    'pilatch-card': Components.PilatchCardAttributes;
  }


  interface HTMLPilatchCardElement extends Components.PilatchCard, HTMLStencilElement {}
  var HTMLPilatchCardElement: {
    prototype: HTMLPilatchCardElement;
    new (): HTMLPilatchCardElement;
  };

  interface HTMLElementTagNameMap {
    'pilatch-card': HTMLPilatchCardElement
  }

  interface ElementTagNameMap {
    'pilatch-card': HTMLPilatchCardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
